spring.application.name=api-rest-catalogs

# PostgreSQL Datasource
spring.datasource.url=jdbc:postgresql://34.31.240.215:5432/${DB_NAME:catalog}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}
spring.datasource.driver-class-name=org.postgresql.Driver

# Jackson
spring.jackson.deserialization.fail-on-unknown-properties=true

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.defer-datasource-initialization=true
spring.jpa.properties.hibernate.format_sql=true

# SQL Init (solo en desarrollo)
spring.sql.init.mode=always

# Server (Cloud Run usa PORT)
server.port=${PORT:8080}

# OpenAPI / Swagger
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
